# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: openandroidinstaller-dev.openandroidinstaller
PackageVersion: 0.5.5-beta
PackageLocale: en-US
Publisher: OpenAndroidInstaller-dev
PublisherUrl: https://github.com/openandroidinstaller-dev
PublisherSupportUrl: https://github.com/openandroidinstaller-dev/openandroidinstaller/issues
PackageName: OpenAndroidInstaller
PackageUrl: https://github.com/openandroidinstaller-dev/openandroidinstaller
License: GPL-3.0
ShortDescription: Makes installing alternative Android distributions nice and easy.
Tags:
- android
- customrom
- hacktoberfest
- lineage-os
- lineageos
- lineageos-devices
- linux
- macos
- open-source
- rom
- twrp
- twrp-recovery
- unofficial
- windows
ReleaseNotesUrl: https://github.com/openandroidinstaller-dev/openandroidinstaller/releases/tag/v0.5.5-beta
ManifestType: defaultLocale
ManifestVersion: 1.10.0
